version: "3.8"


services: 
  backend:
    image: nginx
    container_name: backend
    networks:
      - micro-net
  
  frontend: 
    image: ubuntu
    container_name: frontend
    tty: true
    command: sleep infinity
    networks:
      - micro-net

networks:
  micro-net: